<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXhxfQy6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXhxfQy6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXhxfQy6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXhxfQy6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXhxfQy6\App_KernelDevDebugContainer([
    'container.build_hash' => 'XhxfQy6',
    'container.build_id' => 'ee3af0df',
    'container.build_time' => 1649238848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXhxfQy6');
